### ISSUE TITLE
The problem of authorization of the source code in ImmuneSubtypeClassifier

### ISSUE THREAD

**Issue by huangwb8** [CRI-iAtlas/ImmuneSubtypeClassifier#11]
Recently, I had a problem of classifying samples into subtypes based on several gene signatures.

After reading and testing the source code of ImmuneSubtypeClassifier, I think the basis of ImmuneSubtypeClassifier——Top Scoring Pairs, could be generalized to any new gene signatures, which is my demand.

I had built a new R package (not being pushed onto Github yet) that could classify samples into subtypes based on any gene signatures that users give (including the gene signatures used in ImmuneSubtypeClassifier package).

I plan to publish my paper in the future, and the new package would be part of it. But I‘m not sure whether it is proper to publish it directly, because your source code about Top Scoring Pairs algorithm was deeply referred to.

Would you give some suggestions? Thanks a lot!

**Comment by Gibbsdavidl** [comment]
For historical context: I said "go for it", and "please just cite us".
