### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by crispinhiley** [CRI-iAtlas/ImmuneSubtypeClassifier#12]
many thanks for providing this helpful package. Can you tell me what the input values should be for the matrix. Raw counts? TPM etc? I see from the previous version you say it is sensitive to this. Would be grateful for advice

**Comment by Gibbsdavidl** [comment]
Hi, thanks!
It shouldn't really matter anymore. For the most part it's based on comparing pairs of genes within a sample.  if G1 > G2 then feature = 1 else feature = 0.  Then those features are used in prediction.  Also, there's a couple features that are also found within sample like quartile.  is gene in the upper quartile? feature = 4, etc.    I really need to finish up this paper, but see:  https://www.biorxiv.org/content/10.1101/2020.01.17.910950v1

**Comment by crispinhiley** [comment]
thanks so much for replying so quickly. will have a look

Crispin
